--DROP TABLE USER_ROLES IF EXISTS;
--DROP TABLE USERS IF EXISTS;
--DROP TABLE ROLES IF EXISTS;

--
-- create schema; tables: USERS, ROLES, USER_ROLES
--
CREATE TABLE IF NOT EXISTS USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  is_active BOOLEAN,
  UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS ROLES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  UNIQUE(user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES USERS(id),
  FOREIGN KEY (role_id) REFERENCES ROLES(id)
);